### ISSUE TITLE
pip install broken

### ISSUE THREAD

**Issue by davidmccandlish** [jbkinney/mavenn#28] opened 2023-05-16 20:10 UTC
Current pypi version has a dependency problem with numpy. Suspect this was fixed via commit:
https://github.com/jbkinney/mavenn/commit/af73b51ed34c5243e18f168fb6e422e3eb33e833
but not updated in pypi.

**Comment by atareen** [comment] 2023-05-17 22:34
Thanks David. I'll work on fixing this soon.

**Comment by evanseitz** [comment] 2023-06-07 22:34
Hi @atareen, I'm trying to help David install via `pip install mavenn`, but have now realized that I'm unable to do so as well. I'm getting a `scikit-learn` error to use a different call (see attached image). Apparently, as of Dec. 1, 2022, you have to use `scikit-learn` in pip requirements files as `pip install sklearn` is now deprecated.
- source: https://github.com/scikit-learn/sklearn-pypi-package

<img width="566" alt="mavenn_error" src="https://github.com/jbkinney/mavenn/assets/35609503/07cdaff2-2c41-4040-a9a1-fff978646b01">

___

To reproduce, please try the following:
- `conda create -n mavenn python=3.7`
- `conda activate mavenn`
- `pip install mavenn`

**Comment by atareen** [comment] 2023-06-08 15:43
Hi David and Evan,

Thanks, I am working on this now. There are three issues here. The first is numpy version 1.24.3:
![image](https://github.com/jbkinney/mavenn/assets/6977064/2424673b-9112-4404-a25f-100eed9856be)
This is caused by the latest version of tensorflow (2.12.0), which conflicts with this np version.
![image](https://github.com/jbkinney/mavenn/assets/6977064/b1601dd9-6c36-4b13-a6a0-a606322c11a1)

The second issue, as Evan points out, is sklearn being deprecated. This should be a straight-forward update scikit-learn, however I will need to test this. 

The third issue is the np.bool vs. np.bool_ update, that I will also update (similar to Justin's recent commit https://github.com/jbkinney/mavenn/commit/cc9c376bc416684e62d9e320133c8326e4b1c687)

I will do a new mavenn release on PyPI with address updates; note that there will likely have to be another mavenn release after tensorflow 2.13.0 is deployed, as it addresses fixes the numpy version issue; it's currently released in alpha state (i.e., full deployment releasing soon). 

Thanks,
Ammar

**Comment by evanseitz** [comment] 2023-06-08 15:45
(To note, I think I got around the scikit-learn error by updating my conda base)

**Comment by atareen** [comment] 2023-06-08 15:45
Yes, thanks Evan. Note that my pip install also worked fine and ran the tests and demos okay. So this may be a python version issue. David are you using Python 3.10.*?

**Comment by davidmccandlish** [comment] 2023-06-08 17:19
This was in a fresh Conda environment with Python 3.8 (Conda couldn't find 3.7).

**Comment by atareen** [comment] 2023-06-08 19:45
Hi again, 

I have released mavenn version 1.0.2 where I have removed the deprecated sklearn requirement from setup.py and also the readthedocs_requirements.txt file. I've currently also limited the numpy version to <= 1.23.5 (note that I will update this to the latest version of numpy when the newer tensorflow is released in the near future. At that time I will do another minor point version update release of mavenn). This updates includes Justin's latest commits in model.py - np.bool_ update will be included in the next release. All tests and demos are working/passing.

Note that some conda environments will install the latest version of numpy (1.24.*) upon creation and a subsequent pip install of maven will install version 1.0.1, in this case, please run `pip install mavenn --upgrade` to get mavenn 1.0.2 installed. 

Logging note: prior to release, I tested mavenn 1.0.1 in conda envs using python 3.7, 3.9, and 3.10, and they worked okay for me. I ran into issues when I specifically install numpy 1.24.3. 

@davidmccandlish Please try the updated version and let me know if this works. Thanks.

**Comment by davidmccandlish** [comment] 2023-06-08 22:14
Yes, that works! I did need to do <pip install mavenn --upgrade> to get it to install mavenn 1.0.2.

**Closed** 2023-06-08 22:42 UTC
